# Generated by Django 5.1.2 on 2024-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendauser',
            name='image',
            field=models.ImageField(default='imagesUsers/default.png', upload_to='imagesUsers/'),
        ),
    ]
