# Generated by Django 5.1.1 on 2024-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empanade',
            fields=[
                ('idEmpanada', models.AutoField(primary_key=True, serialize=False)),
                ('nomEmpanada', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('idIngredient', models.AutoField(primary_key=True, serialize=False)),
                ('nomIngredient', models.CharField(max_length=50)),
            ],
        ),
    ]
