# Generated by Django 5.1.1 on 2024-09-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empanadas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empanade',
            new_name='Empanada',
        ),
    ]
