# Generated by Django 5.1.2 on 2024-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanadas', '0003_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanada',
            name='image',
            field=models.ImageField(default='imagesEmpanadas/default.png', upload_to='imagesEmpanadas/'),
        ),
    ]
